[versions]
appcompat = "1.7.1"
ftc = "2.1.2"
fullpanels = "1.0.12"
gradle = "9.2.1"
gradle-toolchains-foojay-resolver-convention = "1.0.0"
ivy = "1.0.0"
vision = "11.1.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
blocks = { module = "org.firstinspires.ftc:Blocks", version.ref = "vision" }
ftc = { module = "com.pedropathing:ftc", version.ref = "ftc" }
ftccommon = { module = "org.firstinspires.ftc:FtcCommon", version.ref = "vision" }
fullpanels = { module = "com.bylazar:fullpanels", version.ref = "fullpanels" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
hardware = { module = "org.firstinspires.ftc:Hardware", version.ref = "vision" }
inspection = { module = "org.firstinspires.ftc:Inspection", version.ref = "vision" }
ivy = { module = "com.pedropathing:ivy", version.ref = "ivy" }
onbotjava = { module = "org.firstinspires.ftc:OnBotJava", version.ref = "vision" }
robotcore = { module = "org.firstinspires.ftc:RobotCore", version.ref = "vision" }
robotserver = { module = "org.firstinspires.ftc:RobotServer", version.ref = "vision" }
telemetry = { module = "com.pedropathing:telemetry", version.ref = "ivy" }
vision = { module = "org.firstinspires.ftc:Vision", version.ref = "vision" }

[plugins]
gradle-toolchains-foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "gradle-toolchains-foojay-resolver-convention" }
